# Use the Nginx image as the base image
FROM nginx:1.21.0-alpine

# Install wget
RUN apk add --no-cache wget

# Download the wait-for-it.sh script
RUN wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -O /wait-for-it.sh

# Make the script executable
RUN chmod +x /wait-for-it.sh

# Copy Nginx configuration file
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
