FROM python:3.10-slim as builder

# Set working directory
WORKDIR /usr/src/app

# Copy requirements file
COPY requirements.txt .

# Upgrade pip and install Python packages
RUN pip install --no-cache-dir --upgrade pip && pip wheel --no-cache-dir --no-deps --wheel-dir /usr/src/app/wheels -r requirements.txt


# pull official base image
FROM python:3.10-slim

# Set working directory
WORKDIR /home/app/ecganalysis

# Create app user and set ownership
RUN mkdir -p ./staticfiles && mkdir -p ./media && groupadd -r app && useradd -r -g app app && chown -R app:app /home/app/ecganalysis && chmod -R 755 /home/app/ecganalysis
RUN apt-get update && \
    apt-get install -y tk && \
    rm -rf /var/lib/apt/lists/*

# Copy wheels and requirements from builder stage
COPY --from=builder /usr/src/app/wheels /wheels
COPY --from=builder /usr/src/app/requirements.txt .

# Install Python packages from wheels
RUN pip install --no-cache-dir /wheels/*

# Copy project files
COPY . .

# Make entrypoint file executable
RUN chmod +x ./bin/entrypoint-django.sh
RUN chmod +x ./bin/entrypoint-celery.sh

# Switch to app user
USER root

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Expose port
EXPOSE 8000