# Generated by Django 4.2.1 on 2023-05-28 13:30

import uuid

import django.core.files.storage
from django.db import migrations, models

import modelling.constants.enums


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initialized", "Initialized"),
                            ("training", "Training"),
                            ("evaluation", "Evaluation"),
                            ("done", "Done"),
                        ],
                        default=modelling.constants.enums.TrainingSessionStatus[
                            "INITIALIZED"
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "kmeans_p_model",
                    models.FileField(
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(
                            location="/Users/eugenereyek/PycharmProjects/EcgAnalysis/modelling/models"
                        ),
                        upload_to="kmeans/",
                    ),
                ),
                (
                    "kmeans_qrs_model",
                    models.FileField(
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(
                            location="/Users/eugenereyek/PycharmProjects/EcgAnalysis/modelling/models"
                        ),
                        upload_to="kmeans/",
                    ),
                ),
                (
                    "kmeans_t_model",
                    models.FileField(
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(
                            location="/Users/eugenereyek/PycharmProjects/EcgAnalysis/modelling/models"
                        ),
                        upload_to="kmeans/",
                    ),
                ),
                (
                    "word2vec_model",
                    models.FileField(
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(
                            location="/Users/eugenereyek/PycharmProjects/EcgAnalysis/modelling/models"
                        ),
                        upload_to="word2vec/",
                    ),
                ),
                (
                    "classifier_model",
                    models.FileField(
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(
                            location="/Users/eugenereyek/PycharmProjects/EcgAnalysis/modelling/models"
                        ),
                        upload_to="classifier/",
                    ),
                ),
                ("classifier_name", models.CharField(blank=True, max_length=100)),
                ("train_accuracy", models.FloatField(null=True)),
                ("test_accuracy", models.FloatField(null=True)),
                ("precision", models.FloatField(null=True)),
                ("recall", models.FloatField(null=True)),
                ("f1_score", models.FloatField(null=True)),
                ("silhouette_score", models.FloatField(null=True)),
                ("charts", models.JSONField(default=dict)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
