# Generated by Django 4.2.1 on 2023-05-28 18:48

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modelling", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingsession",
            name="classifier_model",
            field=models.FileField(
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location="/Users/eugenereyek/PycharmProjects/EcgAnalysis/modelling/models_cache"
                ),
                upload_to="classifier/",
            ),
        ),
        migrations.AlterField(
            model_name="trainingsession",
            name="kmeans_p_model",
            field=models.FileField(
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location="/Users/eugenereyek/PycharmProjects/EcgAnalysis/modelling/models_cache"
                ),
                upload_to="kmeans/",
            ),
        ),
        migrations.AlterField(
            model_name="trainingsession",
            name="kmeans_qrs_model",
            field=models.FileField(
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location="/Users/eugenereyek/PycharmProjects/EcgAnalysis/modelling/models_cache"
                ),
                upload_to="kmeans/",
            ),
        ),
        migrations.AlterField(
            model_name="trainingsession",
            name="kmeans_t_model",
            field=models.FileField(
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location="/Users/eugenereyek/PycharmProjects/EcgAnalysis/modelling/models_cache"
                ),
                upload_to="kmeans/",
            ),
        ),
        migrations.AlterField(
            model_name="trainingsession",
            name="word2vec_model",
            field=models.FileField(
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location="/Users/eugenereyek/PycharmProjects/EcgAnalysis/modelling/models_cache"
                ),
                upload_to="word2vec/",
            ),
        ),
    ]
