# Generated by Django 4.2.1 on 2023-05-28 18:48

import uuid

from django.db import migrations, models

import analysis.constants.enums
import analysis.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalysisSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ecg_file",
                    models.FileField(upload_to=analysis.models.get_ecg_file_upload_to),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initialized", "Initialized"),
                            ("analyzing", "Analyzing"),
                            ("done", "Done"),
                        ],
                        default=analysis.constants.enums.AnalysisSessionStatus[
                            "INITIALIZED"
                        ],
                        max_length=20,
                    ),
                ),
                ("charts", models.JSONField(default=dict)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
