# Generated by Django 4.2.1 on 2023-05-28 23:06

import django.core.validators
from django.db import migrations, models

import analysis.models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysissession",
            name="charts",
        ),
        migrations.RemoveField(
            model_name="analysissession",
            name="status",
        ),
        migrations.AlterField(
            model_name="analysissession",
            name="ecg_file",
            field=models.FileField(
                upload_to=analysis.models.get_ecg_file_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["csv", "xlsx"]
                    )
                ],
            ),
        ),
    ]
