# Generated by Django 4.2.1 on 2023-06-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0002_remove_analysissession_charts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysissession",
            name="fs",
            field=models.IntegerField(default=360),
        ),
    ]
